vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix: /uploads/post
            upload_destination: '%kernel.project_dir%/public/uploads/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
